import BrandCard from "@/components/Brands/Brand-Card/Brand-Card";

export default function Brands() {
  return (
    <section className="flex flex-col justify-start items-start p-main">
        <h1 className="mb-5 text-3xl ">كل الماركات</h1>
        {/**All Brands */}
        <div className="flex flex-wrap justify-between items-start p-main">
                    <BrandCard img={'https://static.vecteezy.com/system/resources/previews/059/250/927/non_2x/stylish-orange-headphones-displayed-on-a-clean-transparent-background-for-modern-audio-enthusiasts-orange-headphone-product-photo-isolated-on-transparent-background-free-png.png'} title={'سماعات رأس'} color= {'red-500'}   className="w-full text-center rounded-full mb-4 cursor-pointer hover:-translate-y-2 transition-transform"/>
                    <BrandCard img={'https://static.vecteezy.com/system/resources/previews/053/178/045/non_2x/clear-blue-bottles-with-pump-dispenser-for-liquid-products-free-png.png'} title={'دواني'} color= {'indigo-500'}   className="w-full text-center rounded-full mb-4 cursor-pointer hover:-translate-y-2 transition-transform"/>
                    <BrandCard img={'https://static.vecteezy.com/system/resources/previews/059/250/927/non_2x/stylish-orange-headphones-displayed-on-a-clean-transparent-background-for-modern-audio-enthusiasts-orange-headphone-product-photo-isolated-on-transparent-background-free-png.png'} title={'تي شيرت رجالي'} color= {'green-500'}   className="w-full text-center rounded-full mb-4 cursor-pointer hover:-translate-y-2 transition-transform"/>
                    <BrandCard img={'https://static.vecteezy.com/system/resources/previews/056/422/303/non_2x/plain-pink-t-shirt-free-png.png'} title={'فأرة كمبيوتر'} color= {'cyan-500'}   className="w-full text-center rounded-full mb-4 cursor-pointer hover:-translate-y-2 transition-transform"/>
                    <BrandCard img={'https://static.vecteezy.com/system/resources/previews/059/250/927/non_2x/stylish-orange-headphones-displayed-on-a-clean-transparent-background-for-modern-audio-enthusiasts-orange-headphone-product-photo-isolated-on-transparent-background-free-png.png'} title={'سماعات رأس'} color= {'blue-500'}   className="w-full text-center rounded-full mb-4 cursor-pointer hover:-translate-y-2 transition-transform"/>
                    <BrandCard img={'https://static.vecteezy.com/system/resources/previews/053/178/045/non_2x/clear-blue-bottles-with-pump-dispenser-for-liquid-products-free-png.png'} title={'دواني'} color= {'fuchsia-500'}   className="w-full text-center rounded-full mb-4 cursor-pointer hover:-translate-y-2 transition-transform"/>
                    <BrandCard img={'https://static.vecteezy.com/system/resources/previews/059/250/927/non_2x/stylish-orange-headphones-displayed-on-a-clean-transparent-background-for-modern-audio-enthusiasts-orange-headphone-product-photo-isolated-on-transparent-background-free-png.png'} title={'سماعات رأس'} color= {'yellow-500'}   className="w-full text-center rounded-full mb-4 cursor-pointer hover:-translate-y-2 transition-transform"/>
                    <BrandCard img={'https://static.vecteezy.com/system/resources/previews/059/250/927/non_2x/stylish-orange-headphones-displayed-on-a-clean-transparent-background-for-modern-audio-enthusiasts-orange-headphone-product-photo-isolated-on-transparent-background-free-png.png'} title={'تي شيرت رجالي'} color= {'gray-500'}   className="w-full text-center rounded-full mb-4 cursor-pointer hover:-translate-y-2 transition-transform"/>
                    <BrandCard img={'https://static.vecteezy.com/system/resources/previews/056/422/303/non_2x/plain-pink-t-shirt-free-png.png'} title={'فأرة كمبيوتر'} color= {'teal-500'}   className="w-full text-center rounded-full mb-4 cursor-pointer hover:-translate-y-2 transition-transform"/>
                    <BrandCard img={'https://static.vecteezy.com/system/resources/previews/059/250/927/non_2x/stylish-orange-headphones-displayed-on-a-clean-transparent-background-for-modern-audio-enthusiasts-orange-headphone-product-photo-isolated-on-transparent-background-free-png.png'} title={'سماعات رأس'} color= {'brown-500'}   className="w-full text-center rounded-full mb-4 cursor-pointer hover:-translate-y-2 transition-transform"/>
                    <BrandCard img={'https://static.vecteezy.com/system/resources/previews/053/178/045/non_2x/clear-blue-bottles-with-pump-dispenser-for-liquid-products-free-png.png'} title={'دواني'} color= {'amber-500'}   className="w-full text-center rounded-full mb-4 cursor-pointer hover:-translate-y-2 transition-transform"/>
                    <BrandCard img={'https://static.vecteezy.com/system/resources/previews/059/250/927/non_2x/stylish-orange-headphones-displayed-on-a-clean-transparent-background-for-modern-audio-enthusiasts-orange-headphone-product-photo-isolated-on-transparent-background-free-png.png'} title={'تي شيرت رجالي'} color= {'orange-500'}   className="w-full text-center rounded-full mb-4 cursor-pointer hover:-translate-y-2 transition-transform"/>
                    <BrandCard img={'https://static.vecteezy.com/system/resources/previews/056/422/303/non_2x/plain-pink-t-shirt-free-png.png'} title={'فأرة كمبيوتر'} color= {'cyan-500'}   className="w-full text-center rounded-full mb-4 cursor-pointer hover:-translate-y-2 transition-transform"/>
        </div>
    </section>
  )
}
